// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models;

public partial class ControleEmprestimoLivroContext : DbContext
{
    public ControleEmprestimoLivroContext(DbContextOptions<ControleEmprestimoLivroContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Livro> Livro { get; set; }

    public virtual DbSet<LivroClienteEmprestimo> LivroClienteEmprestimo { get; set; }

    public virtual DbSet<VwLivroClienteEmprestimo> VwLivroClienteEmprestimo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<LivroClienteEmprestimo>(entity =>
        {
            entity.HasOne(d => d.IdclienteNavigation).WithMany(p => p.LivroClienteEmprestimo).HasConstraintName("FK_livro_cliente_emprestimo_Cliente");

            entity.HasOne(d => d.IdlivroNavigation).WithMany(p => p.LivroClienteEmprestimo).HasConstraintName("FK_livro_cliente_emprestimo_Livro");
        });

        modelBuilder.Entity<VwLivroClienteEmprestimo>(entity =>
        {
            entity.ToView("VW_Livro_Cliente_Emprestimo");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}