// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EmprestimoLivros.API.Models;

[Keyless]
public partial class VwLivroClienteEmprestimo
{
    [Required]
    [Column("bi")]
    [StringLength(25)]
    [Unicode(false)]
    public string Bi { get; set; }

    [Required]
    [Column("nome_cliente")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [Required]
    [Column("nome_livro")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeLivro { get; set; }

    [Column("id")]
    public int Id { get; set; }

    [Column("idlivro")]
    public int? Idlivro { get; set; }

    [Column("idcliente")]
    public int? Idcliente { get; set; }

    [Column("dataEmprestimo", TypeName = "datetime")]
    public DateTime? DataEmprestimo { get; set; }

    [Column("dataDevolucao", TypeName = "datetime")]
    public DateTime? DataDevolucao { get; set; }

    [Column("entregue")]
    public bool Entregue { get; set; }
}